# Generated by Django 4.2.27 on 2025-12-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_uuid', models.CharField(db_index=True, help_text='考試唯一識別碼', max_length=255, unique=True)),
                ('test_name', models.CharField(help_text='考試名稱', max_length=255)),
                ('test_weight', models.CharField(blank=True, default='', help_text='權重', max_length=255)),
                ('test_semester', models.CharField(help_text='學期', max_length=255)),
                ('test_date', models.CharField(help_text='考試日期', max_length=255)),
                ('test_range', models.CharField(help_text='考試範圍', max_length=255)),
                ('pt_opt_score_uuid', models.CharField(blank=True, default='', help_text='指向 NonSQL database test_pic_information', max_length=255)),
                ('test_states', models.CharField(default='尚未出考卷', help_text='狀態: 尚未出考卷/考卷完成/考卷成績結算', max_length=255)),
                ('test_created_at', models.CharField(help_text='建立時間', max_length=255)),
                ('test_updated_at', models.CharField(help_text='更新時間', max_length=255)),
            ],
            options={
                'verbose_name': '考卷',
                'verbose_name_plural': '考卷列表',
                'db_table': 'test',
                'indexes': [models.Index(fields=['test_uuid'], name='test_test_uu_971d30_idx'), models.Index(fields=['test_semester'], name='test_test_se_75cca4_idx'), models.Index(fields=['test_states'], name='test_test_st_6426fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_uuid', models.CharField(db_index=True, help_text='學生唯一識別碼', max_length=255, unique=True)),
                ('student_name', models.CharField(help_text='學生名稱', max_length=255)),
                ('student_number', models.CharField(help_text='學生學號', max_length=255)),
                ('student_semester', models.CharField(help_text='學生學年 (例如: 1141, 1142)', max_length=255)),
                ('student_status', models.CharField(default='修業中', help_text='狀態: 修業中/二退/被當/修業完畢', max_length=255)),
                ('student_created_at', models.CharField(help_text='建立時間', max_length=255)),
                ('student_updated_at', models.CharField(help_text='更新時間', max_length=255)),
            ],
            options={
                'verbose_name': '學生',
                'verbose_name_plural': '學生列表',
                'db_table': 'students',
                'indexes': [models.Index(fields=['student_uuid'], name='students_student_e056bd_idx'), models.Index(fields=['student_semester'], name='students_student_ac2f0e_idx'), models.Index(fields=['student_status'], name='students_student_4fdc35_idx')],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score_uuid', models.CharField(db_index=True, help_text='分數唯一識別碼', max_length=255, unique=True)),
                ('score_quiz1', models.CharField(blank=True, default='', help_text='第一次小考分數', max_length=255)),
                ('score_midterm', models.CharField(blank=True, default='', help_text='期中考分數', max_length=255)),
                ('score_quiz2', models.CharField(blank=True, default='', help_text='第二次小考分數', max_length=255)),
                ('score_finalexam', models.CharField(blank=True, default='', help_text='期末考分數', max_length=255)),
                ('score_total', models.CharField(blank=True, default='', help_text='總分', max_length=255)),
                ('f_student_uuid', models.CharField(db_index=True, help_text='外鍵，關聯到 Students.student_uuid', max_length=255)),
                ('score_created_at', models.CharField(help_text='建立時間', max_length=255)),
                ('score_updated_at', models.CharField(help_text='更新時間', max_length=255)),
            ],
            options={
                'verbose_name': '分數',
                'verbose_name_plural': '分數列表',
                'db_table': 'score',
                'indexes': [models.Index(fields=['score_uuid'], name='score_score_u_3f70a1_idx'), models.Index(fields=['f_student_uuid'], name='score_f_stude_91b962_idx')],
            },
        ),
    ]
