# Generated by Django 4.2.27 on 2025-12-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculus_metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_number',
            field=models.CharField(help_text='學生學號', max_length=255, unique=True),
        ),
    ]
